SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FIGTHER_MARGIN = 100

FIGTHER_DATA_WIDTH = 130
FIGTHER_DATA_HEIGHT = 100

MARGIN_DATA_ROWS = 30

ATTACK_BUTTON_WIDTH = 100
ATTACK_BUTTON_HEIGHT = 20

MARGIN_ATTACK_BUTTONS = 30

WHITE = (255, 255, 255)
FPS = 60

FIGHTER_POSITIONS = [
    (FIGTHER_MARGIN, SCREEN_HEIGHT / 2),
    (SCREEN_WIDTH - FIGTHER_MARGIN, SCREEN_HEIGHT / 2),
]

FIGHTER_DATA_POSITIONS = [
    (FIGTHER_MARGIN * 2.1, SCREEN_HEIGHT / 2),
    (SCREEN_WIDTH - 2.5 * FIGTHER_MARGIN, SCREEN_HEIGHT / 2),
]

FIGTHER_ATTACK_POSITIONS = [
    (FIGTHER_MARGIN, SCREEN_HEIGHT - FIGTHER_MARGIN * 2),
    (SCREEN_WIDTH - FIGTHER_MARGIN, SCREEN_HEIGHT - FIGTHER_MARGIN * 2),
]
